name: py310-cu11-tfrcnn
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.10.11
  - cuda-toolkit=11.8.*
  - cudatoolkit=11.8.*
  - cuda-nvcc=11.8.*
  - pip
  - pip:
    - --extra-index-url https://pypi.nvidia.com tensorrt-libs
    - nvidia-pyindex>=1.0.9
    - nvidia-tensorrt>=99.0.0
    - tensorrt-bindings==8.6.*
    - nvidia-cudnn-cu11==8.6.*
    - tensorflow>=2.12.0
    - tensorflow-datasets>=4.9.2
    - opencv-python>=4.7.0.72
    - click>=8.1.3
    - ruff>=0.0.271
    - yapf>=0.33.0
    - isort>=5.12.0
    - pytest>=7.3.1
    - pytest-cov>=4.1.0
    - ipython
    - jedi-language-server
