name: py311-cu12-tfrcnn
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11.3
  - cuda-toolkit>=12.1.*
  - cuda-nvcc>=12.1.*
  - pip
  - pip:
    - --extra-index-url https://pypi.nvidia.com tensorrt-libs
    - click>=8.1.3
    - nvidia-pyindex>=1.0.9
    - nvidia-cudnn-cu12>=8.9.2.26
    - nvidia-tensorrt>=99.0.0
    - tensorrt-bindings>=8.6.0
    - tensorflow>=2.12.0
    - tensorflow-datasets>=4.9.2
    - opencv-python>=4.7.0.72
    - ruff>=0.0.271
    - yapf>=0.33.0
    - isort>=5.12.0
    - pytest>=7.3.1
    - pytest-cov>=4.1.0
    - ipython
    - jedi-language-server
